### ISSUE TITLE
Удаление канала или группы без аватарки.

### ISSUE THREAD

**Issue by kennerus** [apuc/channels_backend#31]
При удалении канала/группы без аватарки в ответе от сервера приходит status: false и код ответа 302.
Канал/группа из базы удаляется, но данный ответ расценивается как ошибка.

**Comment by kennerus** [comment]
Сервер либо ничего не возвращает, либо слишком много возвращает. В хроме во вкладке "Ответ" ничего не показывает, а в мозиле вкладка "Network" в принципе крашится и просто показывает белый фон.

**Comment by toxa4elovek** [comment]
исправление удаления группы/канала без аватарки
