### ISSUE TITLE
Авторизация через токены на разных компьютерах.

### ISSUE THREAD

**Issue by kennerus** [apuc/channels_backend#33]
При авторизации на разных компьютерах создаются разные токены, после истечения срока действия токена на одном из компьютером отправляется запрос с refresh token, получается токен авторизации. После этого на другом компьютере, когда там истекает время действия токена при отправке refresh token  возвращается 401 и через некоторое время 429 (превышено количество запросов).

**Comment by toxa4elovek** [comment]
Сейчас пользователь может быть авторизован с разных клиентов одновременно?

**Comment by apuc** [comment]
нет

**Comment by kennerus** [comment]
Можно зайти с разных устройств, но токен будет один и тот же. Получается когда время действия токена истекает, на одном устройстве получаем новый, а на другом устройстве остаётся истёкший.

**Comment by kennerus** [comment]
На фронте не правильно была построена логика получения рефреш токена и последующих действий.
