### ISSUE TITLE
Сервер не принимает некоторые изображения.

### ISSUE THREAD

**Issue by kennerus** [apuc/channels_backend#34]
При загрузке некоторых изображений как аватарок на сервер возвращается следующий ответ: [ответ](https://prnt.sc/l60sja)
Картинки: [архив](https://vk.com/doc6463616_478379232?hash=e57df5c6cd6c76a6f0&dl=f3d4e0b3562a1ce5a7)

**Comment by toxa4elovek** [comment]
Исправлены настройки сервера, добавлена валидация аватарок
