### ISSUE TITLE
Email занят при редактировании профиля.

### ISSUE THREAD

**Issue by kennerus** [apuc/channels_backend#36]
При отправке данных редактирования своего профиля [возвращается 422](http://prntscr.com/lbtreb) ответ от сервера - The email has already been taken.

**Comment by kennerus** [comment]
[Ответ](http://prntscr.com/ldhpjq) тот же самый.
[Параметры отправляемые на сервер](http://prntscr.com/ldhpax).

**Comment by toxa4elovek** [comment]
исправление создание и обновления пользователя
