### ISSUE TITLE
Открытие канала

### ISSUE THREAD

**Issue by apuc** [apuc/channels_backend#71]
При открытии канала из группы
![image](https://user-images.githubusercontent.com/6388044/49159112-c8f2bb80-f334-11e8-8149-facee8c8a7d9.png)
1. Скрол сообщений находится вверху. 
![image](https://user-images.githubusercontent.com/6388044/49159161-e58ef380-f334-11e8-9dcc-8690c7e95287.png)
2. При нажатии на кол-во пользователей в канале, в списке нет пользователей. 
![image](https://user-images.githubusercontent.com/6388044/49159216-09ead000-f335-11e8-8fe0-b6e03d81af1b.png)

**Comment by kennerus** [comment]
Запрос на получение пользователей делается, пользователи показываются.
