### ISSUE TITLE
Удалять канал из общего списка, если он в группе.

### ISSUE THREAD

**Issue by kennerus** [apuc/channels_backend#84]

**Comment by kennerus** [comment]
При добавлении канала в группу из стора удаляется этот канал и добавляется в группу.

**Comment by apuc** [comment]
Получается нужно вернуть все каналы которые не состоят в группах и группы? Думаю нужно создать отдельный экшн для получения каналов без групп.

**Comment by kennerus** [comment]
Возвращается массив одинаковых объектов. Различаются по типу.

**Comment by kennerus** [comment]
Странно возвращаются каналы. Часть прикреплённых к группе каналов возвращается только в группе, часть каналов возвращается в общем списке и в группе. 
Примеры:
- в общем списке и группе: [один](http://prntscr.com/nfxk18) [два](http://prntscr.com/nfxl2u)
- [только в группе](http://prntscr.com/nfxks4)
